# Generated by Django 3.2.5 on 2021-07-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='membership',
            new_name='membership_type',
        ),
    ]
