# Generated by Django 3.2.5 on 2021-07-18 09:00

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
    ]
